[pytest]
addopts = -s -v
python_files = *_tests.py test_*.py
python_classes = Test*
python_functions = test_*
markers =
    smoke: Маркировка для смоук-тестов.
    regression: Маркировка для регрессионных тестов.
    navigation: Маркировка для тестов навигации.
    talks: Маркировка для тестов страницы докладов.
    home: Маркировка для тестов главной страницы.
    contacts: Маркировка для тестов страницы контактов.
    memes: Маркировка для тестов страницы мемов.
    chat: Маркировка для тестов чата.
